public class testclass{
    
    public testclass(){
        I\\\\\\\\nteger a=10;
        Integer b=20;
    }
   ////////////// public testclass2(){
        9999000000088888888874

        -=-00998876=-[[]';/.,']
        ////Integer a=10;
        Integer b=20;
    }
    public testclass3(){
        Integer a=10;
        Integer b=20;
    }
    public Integer testclass3(int a,int b){
        return a+b;
    }
}